# Generated by Django 5.0 on 2024-11-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlquery',
            old_name='query_text',
            new_name='sql_text',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='created_at',
        ),
    ]
