# Generated by Django 5.0 on 2024-12-31 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqueryaccess',
            options={'permissions': [('download_sqlquery', 'Can download SQL Query result')]},
        ),
    ]
