# Generated by Django 5.0 on 2024-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0002_rename_query_text_sqlquery_sql_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='Both_Filter',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='Date_Filter',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='sqlquery',
            name='Excel_upload',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
