# Generated by Django 5.0 on 2024-11-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_sqlquery_both_filter_sqlquery_date_filter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlquery',
            old_name='Both_Filter',
            new_name='Add_filter',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='Date_Filter',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='Excel_upload',
        ),
    ]
